{{- /*
=============================================================================
_helpers.tpl - named templates ("partials")

Files whose names start with an underscore are NOT rendered into manifests.
They exist only to define reusable snippets via `define`, which other
templates pull in with `include`.

Anatomy of a definition:

    {{- define "chart.thing" -}}   <- name is global across the chart AND all
    ...body...                        subcharts, hence the "resume." prefix to
    {{- end -}}                       avoid collisions.

`include` vs `template`: both render a named template, but `include` returns
the result as a STRING, which means you can pipe it - `| nindent 4`,
`| sha256sum`, `| quote`. `template` is a statement and cannot be piped. Use
`include` always; there is no case where `template` is better.

Whitespace: `{{-` eats preceding whitespace/newline, `-}}` eats following.
YAML is whitespace-sensitive, so these are load-bearing, not cosmetic. When a
render comes out mangled, this is nearly always why.
=============================================================================
*/}}

{{- /*
The chart name, overridable. `default` returns its SECOND argument if that
argument is non-empty, otherwise the first - so read this as "use
nameOverride, falling back to the chart name".

Names are truncated to 63 chars because that is the limit for a Kubernetes
label value. trimSuffix "-" cleans up the case where truncation lands exactly
on a hyphen, which would be an invalid name.
*/}}
{{- define "resume.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- /*
The fully-qualified app name, used for actual resource names.

The `contains` check avoids the silly "resume-resume" that you would get from
naively concatenating a release named "resume" with a chart named "resume".
This exact logic is in essentially every chart generated by `helm create`.
*/}}
{{- define "resume.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- /*
Chart name + version, for the helm.sh/chart label. `replace "+" "_"` because
SemVer build metadata (1.0.0+build.5) contains a "+", which is illegal in a
label value.
*/}}
{{- define "resume.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- /*
SELECTOR labels - the subset used in Deployment.spec.selector and matched by
the Service.

Kept deliberately separate from the full label set below, and this separation
matters: a Deployment's selector is IMMUTABLE. If version labels were in the
selector, every appVersion bump would make the Deployment un-upgradeable and
you would have to delete and recreate it. Selector labels must be exactly the
stable identity of the workload, nothing more.
*/}}
{{- define "resume.selectorLabels" -}}
app.kubernetes.io/name: {{ include "resume.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}

{{- /*
The full recommended label set, applied to every object's metadata.
Includes the selector labels plus descriptive ones that are free to change.
*/}}
{{- define "resume.labels" -}}
helm.sh/chart: {{ include "resume.chart" . }}
{{ include "resume.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}

{{- /*
A template that takes ARGUMENTS.

Named templates receive exactly one value as their context (the "." inside the
body). Normally that is the root context. To pass more than one thing, build a
map with `dict` and unpack it inside:

    {{ include "resume.componentLabels" (dict "ctx" . "component" "web") }}

Note `.ctx` has to be threaded explicitly into the nested include - inside this
body, "." is the dict, NOT the root context. Forgetting that is the most common
error when writing parameterised helpers: .Values and .Chart simply vanish.
*/}}
{{- define "resume.componentLabels" -}}
{{ include "resume.labels" .ctx }}
app.kubernetes.io/component: {{ .component }}
{{- end -}}

{{- /*
Assemble the image reference.

Demonstrates three things worth stealing:
  - `required` aborts the render with your message if the value is empty.
    Without it a missing value renders as "", and you find out via a confusing
    Kubernetes error much later instead of at template time.

    In THIS chart values.schema.json also enforces image.repository, and the
    schema is checked BEFORE templates render - so clearing image.repository
    produces the schema's error, not this one, and you will not see this
    message in practice. Keep both anyway: the schema guards the value's
    shape, `required` guards the template's assumption, and the two drift
    apart the moment someone edits one without the other.
  - Digest wins over tag when both are set, because digests are immutable.
  - `.Chart.AppVersion` as the tag fallback, so version lives in Chart.yaml.

Variables ($repo, $tag) are assigned with `:=` on first use, `=` to reassign.
*/}}
{{- define "resume.image" -}}
{{- $repo := required "image.repository is required - set it to your resume image" .Values.image.repository -}}
{{- if .Values.image.digest -}}
{{- printf "%s@%s" $repo .Values.image.digest -}}
{{- else -}}
{{- $tag := .Values.image.tag | default .Chart.AppVersion -}}
{{- printf "%s:%s" $repo $tag -}}
{{- end -}}
{{- end -}}

{{- /*
Which ServiceAccount the pod should use. Mirrors the create/name logic in
values.yaml so the Deployment does not have to reason about it.
*/}}
{{- define "resume.serviceAccountName" -}}
{{- if .Values.serviceAccount.create -}}
{{- default (include "resume.fullname" .) .Values.serviceAccount.name -}}
{{- else -}}
{{- default "default" .Values.serviceAccount.name -}}
{{- end -}}
{{- end -}}
